Fix os compatibility tests by enabling multi-platform build and testing

diff --git a/aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.ubuntu.yml b/aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.ubuntu.yml
--- a/aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.ubuntu.yml
+++ b/aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.ubuntu.yml
@@ -4,6 +4,8 @@ env:
   variables:
     OS_DISTRIBUTION: ubuntu
     JAVA_BINARY_LOCATION: "/usr/lib/jvm/java-11-amazon-corretto/bin/java"
+    DOCKER_CLI_EXPERIMENTAL: "enabled"
+    DOCKER_CLI_PLUGIN_DIR: "/root/.docker/cli-plugins"
 batch:
   build-matrix:
     static:
@@ -14,11 +16,15 @@ batch:
       env:
         variables:
           DISTRO_VERSION:
-            - "16.04"
             - "18.04"
             - "20.04"
+            - "21.10"
+            - "22.04"
           RUNTIME_VERSION:
             - "corretto11"
+          PLATFORM:
+            - "linux/amd64"
+            - "linux/arm64/v8"
 phases:
   install:
     commands:
@@ -30,6 +36,34 @@ phases:
             echo "Performing DockerHub login . . ."
             docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
         fi
+      - echo "Setting up multi-arch build environment"
+      - ARCHITECTURE=$(arch)
+      - >
+        if [[ "$ARCHITECTURE" == "x86_64" ]]; then
+            ARCHITECTURE_ALIAS="amd64"
+            TARGET_EMULATOR="arm64"
+        elif [[ "$ARCHITECTURE" == "aarch64" ]]; then
+            ARCHITECTURE_ALIAS="arm64"
+            TARGET_EMULATOR="amd64"
+        else
+            echo "Architecture $ARCHITECTURE is not currently supported."
+            exit 1
+        fi
+      - echo "Installing ${TARGET_EMULATOR} emulator"
+      - docker pull public.ecr.aws/eks-distro-build-tooling/binfmt-misc:qemu-v6.1.0
+      - docker run --rm --privileged public.ecr.aws/eks-distro-build-tooling/binfmt-misc:qemu-v6.1.0 --install ${TARGET_EMULATOR}
+      # Install buildx plugin only if not already present (i.e. it's installed for the local-agent)
+      - >
+        if [[ ! -f "${DOCKER_CLI_PLUGIN_DIR}/docker-buildx" ]]; 
+        then
+            echo "docker-buildx not found, installing now"
+            mkdir -p "${DOCKER_CLI_PLUGIN_DIR}"
+            export BUILDX_URL=$(curl https://api.github.com/repos/docker/buildx/releases/latest | grep browser_download_url | grep "linux-${ARCHITECTURE_ALIAS}" | cut -d '"' -f 4)
+            wget "${BUILDX_URL}" -O "${DOCKER_CLI_PLUGIN_DIR}"/docker-buildx
+            chmod +x "${DOCKER_CLI_PLUGIN_DIR}"/docker-buildx
+        fi
+      - echo "Setting docker build command to default to buildx"
+      - docker buildx install
   pre_build:
     commands:
       # Log some environment variables for troubleshooting
@@ -46,12 +80,12 @@ phases:
       - mkdir "${SCRATCH_DIR}"
       - ARCHITECTURE=$(arch)
       - >
-        if [[ "$ARCHITECTURE" == "x86_64" ]]; then
+        if [[ "$PLATFORM" == "linux/amd64" ]]; then
             RIE="aws-lambda-rie"
-        elif [[ "$ARCHITECTURE" == "aarch64" ]]; then
+        elif [[ "$PLATFORM" == "linux/arm64/v8" ]]; then
             RIE="aws-lambda-rie-arm64"
         else
-            echo "Architecture $ARCHITECTURE is not currently supported."
+            echo "Platform $PLATFORM is not currently supported."
             exit 1
         fi
       - tar -xvf aws-lambda-java-runtime-interface-client/test/integration/resources/${RIE}.tar.gz --directory "${SCRATCH_DIR}"
@@ -69,6 +103,7 @@ phases:
         docker build . \
           -f "${SCRATCH_DIR}/Dockerfile.function.${OS_DISTRIBUTION}.tmp" \
           -t "${IMAGE_TAG}" \
+          --platform="${PLATFORM}" \
           --build-arg RUNTIME_VERSION="${RUNTIME_VERSION}" \
           --build-arg DISTRO_VERSION="${DISTRO_VERSION}"
   build:
